# Generated by Django 5.0.6 on 2024-06-28 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_alter_producto_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestProducto',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('precio', models.IntegerField()),
                ('stock', models.IntegerField()),
                ('imagen', models.ImageField(default='media/default.webp', upload_to='productos/')),
            ],
        ),
    ]
