# Generated by Django 5.0.6 on 2024-06-28 04:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0004_testproducto'),
    ]

    operations = [
        migrations.AddField(
            model_name='testproducto',
            name='categoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tienda.categoria'),
        ),
    ]
