# Generated by Django 5.0.6 on 2024-06-29 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0005_testproducto_categoria'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Producto',
        ),
    ]
