# Generated by Django 5.0.6 on 2024-06-29 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0006_delete_producto'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TestProducto',
            new_name='Producto',
        ),
    ]
