# Generated by Django 5.0.6 on 2024-07-14 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0007_rename_testproducto_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(default='productos/default.webp', upload_to='productos/'),
        ),
    ]
